spring:
  application:
    name: AutoCarrerBridge
  datasource:
    url: jdbc:mysql://localhost:3306/autocareerbridge
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

media:
  img_path: "${user.home}${file.separator}Downloads${file.separator}images"

server:
  servlet:
    context-path: /auto_career
